#!/usr/bin/env bash
set -euo pipefail
ROOT_DEFAULT="/workspaces/QRDS"
ROOT="${QRDS_ROOT:-$(pwd)}"
if [[ ! -d "$ROOT/crypto_decision_lab" && -d "$ROOT_DEFAULT/crypto_decision_lab" ]]; then ROOT="$ROOT_DEFAULT"; fi
if [[ ! -d "$ROOT/crypto_decision_lab" ]]; then echo "[QRDS][Phase40][SERVE] crypto_decision_lab not found" >&2; exit 2; fi
PROJECT_DIR="$ROOT/crypto_decision_lab"
OUT="$PROJECT_DIR/artifacts/phase40_portal_visual_qa_accessibility_link_audit"
HOST="127.0.0.1"
BIND="0.0.0.0"
PORT=""
BUILD=1
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir|--out|--portal-dir) OUT="$2"; shift 2 ;;
    --host) HOST="$2"; shift 2 ;;
    --bind) BIND="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --no-build|--skip-build) BUILD=0; shift ;;
    *) echo "[QRDS][Phase40][SERVE] Unknown arg: $1" >&2; exit 2 ;;
  esac
done
if [[ "$OUT" != /* ]]; then OUT="$ROOT/$OUT"; fi
cd "$PROJECT_DIR"
export PYTHONPATH="$PROJECT_DIR/src:$PROJECT_DIR:${PYTHONPATH:-}"
if [[ "$BUILD" == "1" ]]; then
  python "$PROJECT_DIR/scripts/phase40_portal_visual_qa_accessibility_link_audit.py" --output-dir "$OUT"
fi
if [[ ! -f "$OUT/index.html" ]]; then
  echo '<!doctype html><html><head><meta charset="utf-8"><title>QRDS Phase 40</title></head><body><h1>QRDS Phase 40</h1><p>index fallback generated by serve wrapper.</p></body></html>' > "$OUT/index.html"
fi
if [[ -z "$PORT" ]]; then
  PORT=$(python - <<'PY_PORT'
import socket
for port in range(8780, 8880):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        try:
            s.bind(("127.0.0.1", port))
        except OSError:
            continue
        print(port)
        break
else:
    raise SystemExit("no available port")
PY_PORT
)
fi
python - <<PY_PLAN
import json
from pathlib import Path
out = Path("$OUT")
plan = {
  "phase": 40,
  "portal_dir": str(out),
  "host": "$HOST",
  "bind": "$BIND",
  "port": int("$PORT"),
  "url": f"http://$HOST:{int('$PORT')}/",
  "codespaces_ports_instruction": "Abra a aba Ports no Codespaces, encontre a porta impressa, defina visibility se necessário e clique no link/ícone de abrir no navegador.",
  "research_only": True,
  "operational_status": "BLOCKED_RESEARCH_ONLY",
}
(out / "dashboard_serve_plan.json").write_text(json.dumps(plan, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(json.dumps(plan, ensure_ascii=False, indent=2))
PY_PLAN
cd "$OUT"
echo "[QRDS][Phase40][SERVE] Serving $OUT on $BIND:$PORT"
echo "[QRDS][Phase40][SERVE] Codespaces: aba Ports -> porta $PORT -> abrir no navegador."
python -m http.server "$PORT" --bind "$BIND"
