from pathlib import Path

ROOT = Path(__file__).resolve().parent


def test_required_prereg_artifacts_exist():
    required = [
        "WIN_WDO_CROSS_ASSET_REGIME_PREREG_20260915.json",
        "WIN_WDO_CROSS_ASSET_REGIME_ANALYSIS_FREEZE_20260915.json",
        "WIN_WDO_CROSS_ASSET_REGIME_DISCOVERY_SPEC_20260915.json",
        "WIN_WDO_CROSS_ASSET_REGIME_REGIME_BREAK_SPEC_20260915.json",
        "WIN_WDO_CROSS_ASSET_REGIME_SOURCE_AUDIT_PLAN_20260915.json",
        "WIN_WDO_CROSS_ASSET_REGIME_COST_BOUNDARY_20260915.json",
        "WIN_WDO_CROSS_ASSET_REGIME_PROMOTION_GATE_20260915.json",
        "WIN_WDO_CROSS_ASSET_REGIME_PROSPECTIVE_BOUNDARY_20260915.json",
        "WIN_WDO_CROSS_ASSET_REGIME_NO_TRADES_AUDIT_BOUNDARY_20260915.json",
        "WIN_WDO_CROSS_ASSET_REGIME_CUTOFF_20260915.json",
        "WIN_WDO_CROSS_ASSET_REGIME_REJECTION_LEDGER_20260915.jsonl",
    ]
    assert all((ROOT / x).exists() for x in required)
